import NavMain from "@/components/global/app-sidebar/nav-main";
import { HomeIcon, LayoutTemplateIcon, SettingsIcon, TrashIcon } from "lucide-react";
import { Theme } from "./types";

export const data = {
    user:{
        name:'samuel',
        email:'m@example.com',
        avatar:'/avatars/shadcn.jpg',
    },
    navMain:[{
        title: "Home",
        url: "/dashboard",
        icon:HomeIcon,
    },
    {
        title: "Templates",
        url: "/templates",
        icon:LayoutTemplateIcon,
    },
    {
        title: "Trash",
        url: "/trash",
        icon:TrashIcon,
    },
    {
        title: "Settings",
        url: "/settings",
        icon:SettingsIcon,
    }
]
}

export const containerVariants = {
    hidden: {opacity: 0},
    visible: {opacity: 1, transition: {staggerChildren: 0.1}}
}

export const itemVariants = {
    hidden: {y:20, opacity: 0},
    visible: {
        y:0,
        opacity: 1,
        transition: {
            type: "spring",
            stiffness: 100,
            // damping: 20
        }
    }
}

export const themes: Theme[] = [
    {
    name: 'Theme1 - Light',
    fontFamily: "'Inter', sans-serif",
    fontColor: '#1f1f1f', // dark gray for soft contrast
    backgroundColor: '#f5f5f5', // light, soft white background
    slideBackgroundColor: '#ffffff', // white slides for clarity
    accentColor: '#e35a2f', // original accent for identity
    navbarColor: '#f0f0f0', // lighter navbar
    sidebarColor: '#eaeaea', // soft sidebar tone
    type: 'light', // light mode theme
}

,
    {
        name: 'Theme2',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#83cb05',
        backgroundColor: '#9991c3',
        slideBackgroundColor: '#82136e',
        accentColor: '#5ae136',
        navbarColor: '#db32e5',
        sidebarColor: '#70a2f7',
        type: 'dark',
    },
    {
        name: 'Theme3',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#80e003',
        backgroundColor: '#38f5d0',
        slideBackgroundColor: '#a5f17b',
        accentColor: '#6a182b',
        navbarColor: '#b5c375',
        sidebarColor: '#44a4cb',
        type: 'light',
    },
    {
        name: 'Theme4',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#3f71b1',
        backgroundColor: '#f7851a',
        slideBackgroundColor: '#4ef1ff',
        accentColor: '#aa297d',
        navbarColor: '#d7e4b0',
        sidebarColor: '#aa4012',
        type: 'light',
    },
    {
        name: 'Theme5',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#7b3b8f',
        backgroundColor: '#0fc2a7',
        slideBackgroundColor: '#cabd3c',
        accentColor: '#91ec26',
        navbarColor: '#d2c254',
        sidebarColor: '#5a6a61',
        type: 'dark',
    },
    {
        name: 'Theme6',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#f01e42',
        backgroundColor: '#dff0d7',
        slideBackgroundColor: '#9d2bcd',
        accentColor: '#f5904d',
        navbarColor: '#73bd0a',
        sidebarColor: '#4a4961',
        type: 'light',
    },
    {
        name: 'Theme7',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#6ae831',
        backgroundColor: '#231143',
        slideBackgroundColor: '#7fae9a',
        accentColor: '#872fe9',
        navbarColor: '#b4e23d',
        sidebarColor: '#fa5c83',
        type: 'dark',
    },
    {
        name: 'Theme8',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#8c73cc',
        backgroundColor: '#3e805b',
        slideBackgroundColor: '#b9a168',
        accentColor: '#ff5db3',
        navbarColor: '#b4bcb0',
        sidebarColor: '#e338b1',
        type: 'light',
    },
    {
        name: 'Theme9',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#76cd53',
        backgroundColor: '#fec489',
        slideBackgroundColor: '#3f4b59',
        accentColor: '#bc091a',
        navbarColor: '#45a4c7',
        sidebarColor: '#ff9002',
        type: 'light',
    },
    {
        name: 'Theme10',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#2310c0',
        backgroundColor: '#ffee0c',
        slideBackgroundColor: '#23f67f',
        accentColor: '#ea4955',
        navbarColor: '#4a04ff',
        sidebarColor: '#90fe7f',
        type: 'dark',
    },
    {
        name: 'Theme11',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#5dc24e',
        backgroundColor: '#c591f4',
        slideBackgroundColor: '#7160a0',
        accentColor: '#d04630',
        navbarColor: '#1be2f6',
        sidebarColor: '#f6df5b',
        type: 'light',
    },
    {
        name: 'Theme12',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#1e21d0',
        backgroundColor: '#2c8756',
        slideBackgroundColor: '#e3c3a9',
        accentColor: '#aaefc2',
        navbarColor: '#b00fd1',
        sidebarColor: '#f88809',
        type: 'dark',
    },
    {
        name: 'Theme13',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#cdbb78',
        backgroundColor: '#96fd7f',
        slideBackgroundColor: '#f0c512',
        accentColor: '#8e3c66',
        navbarColor: '#799a9b',
        sidebarColor: '#b33d16',
        type: 'light',
    },
    {
        name: 'Theme14',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#57b22f',
        backgroundColor: '#d1bb3f',
        slideBackgroundColor: '#1b47ae',
        accentColor: '#3baf21',
        navbarColor: '#cd792a',
        sidebarColor: '#3c9f67',
        type: 'dark',
    },
    {
        name: 'Theme15',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#8a038e',
        backgroundColor: '#60da4a',
        slideBackgroundColor: '#e7a8b5',
        accentColor: '#1a7d91',
        navbarColor: '#be267f',
        sidebarColor: '#557cf0',
        type: 'light',
    },
    {
        name: 'Theme16',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#f04661',
        backgroundColor: '#9e23cf',
        slideBackgroundColor: '#bfcba2',
        accentColor: '#8cda53',
        navbarColor: '#8b724e',
        sidebarColor: '#2974f4',
        type: 'dark',
    },
    {
        name: 'Theme17',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#4bb6c1',
        backgroundColor: '#3dfc80',
        slideBackgroundColor: '#e7b874',
        accentColor: '#c3358c',
        navbarColor: '#d1d637',
        sidebarColor: '#f45e2f',
        type: 'light',
    },
    {
        name: 'Theme18',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#7546e1',
        backgroundColor: '#e3c765',
        slideBackgroundColor: '#45c187',
        accentColor: '#ec4c3c',
        navbarColor: '#3251b0',
        sidebarColor: '#96e9a6',
        type: 'dark',
    },
    {
        name: 'Theme19',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#e41c53',
        backgroundColor: '#4c5c69',
        slideBackgroundColor: '#ffe0e3',
        accentColor: '#7bc42b',
        navbarColor: '#82cd4a',
        sidebarColor: '#e7859b',
        type: 'light',
    },
    {
        name: 'Theme20',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#dfdc62',
        backgroundColor: '#542f97',
        slideBackgroundColor: '#2fc6a7',
        accentColor: '#f16712',
        navbarColor: '#be57d1',
        sidebarColor: '#bdf05c',
        type: 'dark',
    },
    {
        name: 'Theme21',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#57f41c',
        backgroundColor: '#a29076',
        slideBackgroundColor: '#c02768',
        accentColor: '#7aa738',
        navbarColor: '#e89ff3',
        sidebarColor: '#1e85b0',
        type: 'light',
    },
    {
        name: 'Theme22',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#9dbef5',
        backgroundColor: '#1a6b6e',
        slideBackgroundColor: '#f5d7ce',
        accentColor: '#23b1cd',
        navbarColor: '#a70f2e',
        sidebarColor: '#adf04e',
        type: 'dark',
    },
    {
        name: 'Theme23',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#f83dc2',
        backgroundColor: '#62777d',
        slideBackgroundColor: '#54f47f',
        accentColor: '#f50c80',
        navbarColor: '#d6de7f',
        sidebarColor: '#e1a75b',
        type: 'light',
    },
    {
        name: 'Theme24',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#9f1e76',
        backgroundColor: '#e9c04d',
        slideBackgroundColor: '#3b7df3',
        accentColor: '#1e5746',
        navbarColor: '#68fbae',
        sidebarColor: '#7e6295',
        type: 'dark',
    },
    {
        name: 'Theme25',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#0a8ab7',
        backgroundColor: '#cc788e',
        slideBackgroundColor: '#c7a54b',
        accentColor: '#7cf0e7',
        navbarColor: '#1a8d60',
        sidebarColor: '#ff694c',
        type: 'light',
    },
    {
        name: 'Theme26',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#302bb1',
        backgroundColor: '#f27a0d',
        slideBackgroundColor: '#75eac2',
        accentColor: '#c59c0f',
        navbarColor: '#6294ff',
        sidebarColor: '#14d3b6',
        type: 'dark',
    },
    {
        name: 'Theme27',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#a83bc7',
        backgroundColor: '#e0dcbd',
        slideBackgroundColor: '#8dbac1',
        accentColor: '#ddf237',
        navbarColor: '#9c5361',
        sidebarColor: '#e7f06d',
        type: 'light',
    },
    {
        name: 'Theme28',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#4de1fc',
        backgroundColor: '#6a1ea9',
        slideBackgroundColor: '#da6c3c',
        accentColor: '#fff254',
        navbarColor: '#8c83d3',
        sidebarColor: '#97e4bc',
        type: 'dark',
    },
    {
        name: 'Theme29',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#cb0ba5',
        backgroundColor: '#d4a372',
        slideBackgroundColor: '#72f0b2',
        accentColor: '#576bfc',
        navbarColor: '#eec327',
        sidebarColor: '#3f3422',
        type: 'light',
    },
    {
        name: 'Theme30',
        fontFamily: "'Inter', sans-serif",
        fontColor: '#b63d07',
        backgroundColor: '#eaff47',
        slideBackgroundColor: '#d36785',
        accentColor: '#4e4cdb',
        navbarColor: '#42e7c6',
        sidebarColor: '#2e967b',
        type: 'dark',
    },
];


export const CreatePageCard = [
    {
        title: 'Use a',
        highlightedText: 'Template',
        description: 'Write a prompt and leave everything else for us to handle',
        type: 'template',
    },
    {
        title: 'Generate with',
        highlightedText: 'Creative AI',
        description: 'Write a prompt and leave everything else for us to handle',
        type: 'creative-ai', 
        highlight:true
    },

  { title: 'Create from',
    highlightedText: 'Scratch',
    description: 'Write a prompt and leave everything else for us to handle',
    type: 'create-scratch',
}
]