import NavMain from "@/components/global/app-sidebar/nav-main";
import { HomeIcon, LayoutTemplateIcon, SettingsIcon, TrashIcon } from "lucide-react";
import { ComponentGroup, LayoutGroup, LayoutSlides, Theme } from "@/lib/types";
import {
  BlankCard,
  AccentLeft,
  AccentRight,
  ImageAndText,
  TextAndImage,
  TwoColumns,
  ThreeColumns,
  TwoColumnsWithHeadings,
  ThreeColumnsWithHeadings,
  FourColumns,
  TwoImageColumns,
  FourImageColumns,
  ThreeImageColumns,
} from "@/lib/slideLayouts";
import {
  BlankCardIcon,
  FourColumnsIcon,
  FourImageColumnsIcon,
  ImageAndTextIcon,
  TextAndImageIcon,
  ThreeColumnsIcon,
  ThreeColumnsWithHeadingsIcon,
  ThreeImageColumnsIcon,
  TwoColumnsIcon,
  TwoColumnsWithHeadingsIcon,
  TwoImageColumnsIcon,
} from "./icons-Component";
import {
  BulletListComponent,
  CalloutBoxComponent,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  NumberedListComponent,
  Paragraph,
  ResizableColumn,
  Table,
  Title,
  TodoListComponent,
} from "./slideComponent";

export const data = {
    user:{
        name:'samuel',
        email:'m@example.com',
        avatar:'/avatars/shadcn.jpg',
    },
    navMain:[{
        title: "Home",
        url: "/dashboard",
        icon:HomeIcon,
    },
    {
        title: "Templates",
        url: "/templates",
        icon:LayoutTemplateIcon,
    },
    {
        title: "Trash",
        url: "/trash",
        icon:TrashIcon,
    },
    {
        title: "Settings",
        url: "/settings",
        icon:SettingsIcon,
    }
]
}



export const containerVariants = {
    hidden: {opacity: 0},
    visible: {opacity: 1, transition: {staggerChildren: 0.1}}
}

export const itemVariants = {
    hidden: {y:20, opacity: 0},
    visible: {
        y:0,
        opacity: 1,
        transition: {
            type: "spring",
            stiffness: 100,
            // damping: 20
        }
    }
}

export const themes: Theme[] = [
    {
        name: "Default",
        fontFamily: "'Inter', sans-serif",
        fontColor: "#000000",
        backgroundColor: "#f0f0f0",
        slideBackgroundColor: "#ffffff",
        accentColor: "#3b82f6",
        navbarColor: "#ffffff",
        sidebarColor: "#f0f0f0",
        type: "light",
    },
    {
    name: "Celestial Horizon",
    fontFamily: "'DM Sans', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1a1a2e",
    slideBackgroundColor: "#16213e",
    accentColor: "#ff6a00",
    gradientBackground: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    navbarColor: "#16213e",
    sidebarColor: "#1a1a2e",
    type: "dark",
  },
  {
  name: "Executive Platinum",
  fontFamily: "'Inter', sans-serif",
  fontColor: "#1a1a1a",
  backgroundColor: "#f4f6f8",
  slideBackgroundColor: "#ffffff",
  accentColor: "#4b6cb7",
  gradientBackground: "linear-gradient(135deg, #f4f6f8 0%, #d7dde8 50%, #cbd2e0 100%)",
  navbarColor: "#e0e7ff",
  sidebarColor: "#f4f6f8",
  type: "light",
},
{
  name: "Royal Obsidian",
  fontFamily: "'IBM Plex Sans', sans-serif",
  fontColor: "#ffffff",
  backgroundColor: "#1a1b2f",
  slideBackgroundColor: "#2c2c54",
  accentColor: "#8e44ad",
  gradientBackground: "linear-gradient(135deg, #2c2c54 0%, #4b0082 100%)",
  navbarColor: "#2c2c54",
  sidebarColor: "#1a1b2f",
  type: "dark",
}
,

  {
    name: "Opal Mist",
    fontFamily: "'Urbanist', sans-serif",
    fontColor: "#1f2937",
    backgroundColor: "#fef9ff",
    slideBackgroundColor: "#ffffff",
    accentColor: "#a78bfa",
    gradientBackground: "linear-gradient(135deg, #fef9ff 0%, #e0c3fc 100%)",
    navbarColor: "#f3e8ff",
    sidebarColor: "#fef9ff",
    type: "light",
  },
  {
    name: "Velvet Inferno",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#2a0f35",
    slideBackgroundColor: "#3a0d4e",
    accentColor: "#ff007f",
    gradientBackground: "linear-gradient(135deg, #3a0d4e 0%, #b3127d 100%)",
    navbarColor: "#3a0d4e",
    sidebarColor: "#2a0f35",
    type: "dark",
  },
  {
    name: "Serene Prism",
    fontFamily: "'Outfit', sans-serif",
    fontColor: "#202020",
    backgroundColor: "#fdfbfb",
    slideBackgroundColor: "#ffffff",
    accentColor: "#00bcd4",
    gradientBackground: "linear-gradient(135deg, #fdfbfb 0%, #ebedee 100%)",
    navbarColor: "#ebedee",
    sidebarColor: "#fdfbfb",
    type: "light",
  },
  {
    name: "Neon Mirage",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f0f0f",
    slideBackgroundColor: "#1e1e1e",
    accentColor: "#00ffe7",
    gradientBackground: "linear-gradient(135deg, #ff00cc 0%, #333399 100%)",
    navbarColor: "#1e1e1e",
    sidebarColor: "#0f0f0f",
    type: "dark",
  },
    {
    name: "Galaxy Drift",
    fontFamily: "'Space Grotesk', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f2027",
    slideBackgroundColor: "#203a43",
    accentColor: "#ff4e50",
    gradientBackground: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
    navbarColor: "#203a43",
    sidebarColor: "#0f2027",
    type: "dark",
  },
  {
    name: "Peach Mango Smoothie",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#4a4a4a",
    backgroundColor: "#ffe0c3",
    slideBackgroundColor: "#fff5e1",
    accentColor: "#ffb347",
    gradientBackground: "linear-gradient(135deg, #ffecd2 0%, #ffe0c3 100%)",
    navbarColor: "#fff5e1",
    sidebarColor: "#ffe0c3",
    type: "light",
  },
  {
    name: "Midnight Aurora",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#2c3e50",
    slideBackgroundColor: "#1c2833",
    accentColor: "#00c9ff",
    gradientBackground: "linear-gradient(135deg, #4b6cb7 0%, #182848 100%)",
    navbarColor: "#1c2833",
    sidebarColor: "#2c3e50",
    type: "dark",
  },
  {
    name: "Desert Mirage",
    fontFamily: "'Merriweather', serif",
    fontColor: "#3e2723",
    backgroundColor: "#ffebd6",
    slideBackgroundColor: "#ffffff",
    accentColor: "#d2691e",
    gradientBackground: "linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)",
    navbarColor: "#fff3e0",
    sidebarColor: "#ffebd6",
    type: "light",
  },
  {
    name: "Lush Vibes",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#005c97",
    slideBackgroundColor: "#363795",
    accentColor: "#43cea2",
    gradientBackground: "linear-gradient(135deg, #005c97 0%, #363795 100%)",
    navbarColor: "#363795",
    sidebarColor: "#005c97",
    type: "dark",
  },
     {
    name: "Pink Lemonade",
    fontFamily: "'Roboto', sans-serif",
    fontColor: "#3d3d3d",
    backgroundColor: "#ffdde1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ee9ca7",
    gradientBackground: "linear-gradient(135deg, #ffdde1 0%, #ee9ca7 100%)",
    navbarColor: "#ee9ca7",
    sidebarColor: "#ffdde1",
    type: "light",
  },
  {
    name: "Cyberpunk Neon",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f0c29",
    slideBackgroundColor: "#302b63",
    accentColor: "#ff0080",
    gradientBackground: "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #ff0080 100%)",
    navbarColor: "#302b63",
    sidebarColor: "#0f0c29",
    type: "dark",
  },
  {
    name: "Cotton Candy",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#333333",
    backgroundColor: "#fcb69f",
    slideBackgroundColor: "#ffecd2",
    accentColor: "#fc6767",
    gradientBackground: "linear-gradient(135deg, #fcb69f 0%, #ffecd2 100%)",
    navbarColor: "#ffecd2",
    sidebarColor: "#fcb69f",
    type: "light",
  },
  
  {
    name: "Ocean Sunrise",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#2c3e50",
    backgroundColor: "#00c6ff",
    slideBackgroundColor: "#ffffff",
    accentColor: "#0072ff",
    gradientBackground: "linear-gradient(135deg, #fdbb2d 0%, #22c1c3 100%)",
    navbarColor: "#22c1c3",
    sidebarColor: "#00c6ff",
    type: "light",
  },
  {
    name: "Mystic Forest",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#e0f2f1",
    backgroundColor: "#1b5e20",
    slideBackgroundColor: "#2e7d32",
    accentColor: "#66bb6a",
    gradientBackground: "linear-gradient(135deg, #1b5e20 0%, #2e7d32 100%)",
    navbarColor: "#2e7d32",
    sidebarColor: "#1b5e20",
    type: "dark",
  },
  {
    name: "Velvet Night",
    fontFamily: "'Merriweather', serif",
    fontColor: "#f1f1f1",
    backgroundColor: "#141e30",
    slideBackgroundColor: "#243b55",
    accentColor: "#ff6a00",
    gradientBackground: "linear-gradient(135deg, #141e30 0%, #243b55 100%)",
    navbarColor: "#243b55",
    sidebarColor: "#141e30",
    type: "dark",
  },
    {
    name: "Aurora Sky",
    fontFamily: "'Inter', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1e3c72",
    slideBackgroundColor: "#2a5298",
    accentColor: "#4facfe",
    gradientBackground: "linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)",
    navbarColor: "#2a5298",
    sidebarColor: "#1e3c72",
    type: "dark",
  },
  {
    name: "Peach Sunrise",
    fontFamily: "'Lora', serif",
    fontColor: "#4a2c2a",
    backgroundColor: "#ffe5b4",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ff7e5f",
    gradientBackground: "linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)",
    navbarColor: "#fcb69f",
    sidebarColor: "#ffecd2",
    type: "light",
  },
  {
    name: "Citrus Splash",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#333333",
    backgroundColor: "#fffbe6",
    slideBackgroundColor: "#ffffff",
    accentColor: "#f9d423",
    gradientBackground: "linear-gradient(135deg, #f9d423 0%, #ff4e50 100%)",
    navbarColor: "#ff4e50",
    sidebarColor: "#fffbe6",
    type: "light",
  },
  {
    name: "Royal Prism",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#360033",
    slideBackgroundColor: "#0b8793",
    accentColor: "#d38312",
    gradientBackground: "linear-gradient(135deg, #360033 0%, #0b8793 100%)",
    navbarColor: "#0b8793",
    sidebarColor: "#360033",
    type: "dark",
  },
  {
    name: "Frosted Mint",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#1c1c1c",
    backgroundColor: "#dff9fb",
    slideBackgroundColor: "#ffffff",
    accentColor: "#00cec9",
    gradientBackground: "linear-gradient(135deg, #dff9fb 0%, #00cec9 100%)",
    navbarColor: "#00cec9",
    sidebarColor: "#dff9fb",
    type: "light",
  },
  {
    name: "Galaxy Dream",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1d2671",
    slideBackgroundColor: "#c33764",
    accentColor: "#8e2de2",
    gradientBackground: "linear-gradient(135deg, #1d2671 0%, #c33764 100%)",
    navbarColor: "#c33764",
    sidebarColor: "#1d2671",
    type: "dark",
  },
  {
    name: "Coral Bloom",
    fontFamily: "'Montserrat', sans-serif",
    fontColor: "#4a4a4a",
    backgroundColor: "#ffecd2",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ff6f61",
    gradientBackground: "linear-gradient(135deg, #ff9a9e 0%, #fecfef 100%)",
    navbarColor: "#fecfef",
    sidebarColor: "#ffecd2",
    type: "light",
  },
  {
    name: "Cyber Pulse",
    fontFamily: "'IBM Plex Mono', monospace",
    fontColor: "#00ffcc",
    backgroundColor: "#000000",
    slideBackgroundColor: "#111111",
    accentColor: "#00ffcc",
    gradientBackground: "linear-gradient(135deg, #000000 0%, #00ffcc 100%)",
    navbarColor: "#111111",
    sidebarColor: "#000000",
    type: "dark",
  },
  {
    name: "Candy Pop",
    fontFamily: "'Pacifico', cursive",
    fontColor: "#4b0082",
    backgroundColor: "#ffe5ec",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ff69b4",
    gradientBackground: "linear-gradient(135deg, #fbc2eb 0%, #a6c1ee 100%)",
    navbarColor: "#fbc2eb",
    sidebarColor: "#ffe5ec",
    type: "light",
  },
  {
    name: "Steel Twilight",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#f1f1f1",
    backgroundColor: "#2c3e50",
    slideBackgroundColor: "#34495e",
    accentColor: "#95a5a6",
    gradientBackground: "linear-gradient(135deg, #2c3e50 0%, #4ca1af 100%)",
    navbarColor: "#34495e",
    sidebarColor: "#2c3e50",
    type: "dark",
  },
  {
    name: "Sunset Dusk",
    fontFamily: "'Merriweather', serif",
    fontColor: "#fff8f0",
    backgroundColor: "#ff758c",
    slideBackgroundColor: "#ff7eb3",
    accentColor: "#ff6a00",
    gradientBackground: "linear-gradient(135deg, #ff758c 0%, #ff7eb3 100%)",
    navbarColor: "#ff7eb3",
    sidebarColor: "#ff758c",
    type: "dark",
  },
  {
    name: "Tropical Bliss",
    fontFamily: "'Raleway', sans-serif",
    fontColor: "#344e41",
    backgroundColor: "#d8f3dc",
    slideBackgroundColor: "#ffffff",
    accentColor: "#40916c",
    gradientBackground: "linear-gradient(135deg, #d8f3dc 0%, #95d5b2 100%)",
    navbarColor: "#95d5b2",
    sidebarColor: "#d8f3dc",
    type: "light",
  },
  {
    name: "Fire Ember",
    fontFamily: "'Roboto Slab', serif",
    fontColor: "#ffffff",
    backgroundColor: "#a40606",
    slideBackgroundColor: "#d98324",
    accentColor: "#ff4500",
    gradientBackground: "linear-gradient(135deg, #a40606 0%, #d98324 100%)",
    navbarColor: "#d98324",
    sidebarColor: "#a40606",
    type: "dark",
  },
  {
    name: "Skyline Blue",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#1e3c72",
    backgroundColor: "#dbeafe",
    slideBackgroundColor: "#ffffff",
    accentColor: "#3b82f6",
    gradientBackground: "linear-gradient(135deg, #dbeafe 0%, #93c5fd 100%)",
    navbarColor: "#93c5fd",
    sidebarColor: "#dbeafe",
    type: "light",
  },
  {
    name: "Velvet Rose",
    fontFamily: "'Lato', sans-serif",
    fontColor: "#fffaf0",
    backgroundColor: "#990000",
    slideBackgroundColor: "#ff3366",
    accentColor: "#ff0033",
    gradientBackground: "linear-gradient(135deg, #990000 0%, #ff3366 100%)",
    navbarColor: "#ff3366",
    sidebarColor: "#990000",
    type: "dark",
  },
  {
    name: "Purple Mirage",
    fontFamily: "'Rubik', sans-serif",
    fontColor: "#e0d7f5",
    backgroundColor: "#9d50bb",
    slideBackgroundColor: "#6e48aa",
    accentColor: "#d291bc",
    gradientBackground: "linear-gradient(135deg, #9d50bb 0%, #6e48aa 100%)",
    navbarColor: "#6e48aa",
    sidebarColor: "#9d50bb",
    type: "dark",
  },
  {
    name: "Lime Spark",
    fontFamily: "'Ubuntu', sans-serif",
    fontColor: "#1b1b1b",
    backgroundColor: "#e8f5e9",
    slideBackgroundColor: "#ffffff",
    accentColor: "#76ff03",
    gradientBackground: "linear-gradient(135deg, #ccff90 0%, #76ff03 100%)",
    navbarColor: "#ccff90",
    sidebarColor: "#e8f5e9",
    type: "light",
  },
  {
    name: "Bubblegum Pop",
    fontFamily: "'Comic Neue', cursive",
    fontColor: "#292929",
    backgroundColor: "#fce4ec",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ec407a",
    gradientBackground: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
    navbarColor: "#f8bbd0",
    sidebarColor: "#fce4ec",
    type: "light",
  },
  {
  name: "Ocean Depth",
  fontFamily: "'DM Sans', sans-serif",
  fontColor: "#e0f7fa", // Soft aqua for text
  backgroundColor: "#001f3f", // Deep ocean navy
  slideBackgroundColor: "#003b73", // Blue abyss
  accentColor: "#00bcd4", // Ocean turquoise
  gradientBackground: "linear-gradient(135deg, #001f3f 0%, #00587a 100%)",
  navbarColor: "#002b4f",
  sidebarColor: "#001f3f",
  type: "dark",
},

  {
  name: "Crimson Canvas",
  fontFamily: "'Poppins', sans-serif",
  fontColor: "#ffffff",
  backgroundColor: "#8B0000", // Darker crimson
  slideBackgroundColor: "#b22222", // Firebrick red
  accentColor: "#ff6b6b", // Soft red-pink accent for contrast
  gradientBackground: "linear-gradient(135deg, #8B0000 0%, #b22222 100%)",
  navbarColor: "#a52a2a",
  sidebarColor: "#8B0000",
  type: "dark",
},

    {
    name: "Crystal Sky",
    fontFamily: "'Rubik', sans-serif",
    fontColor: "#1e3a8a",
    backgroundColor: "#e0f2fe",
    slideBackgroundColor: "#ffffff",
    accentColor: "#38bdf8",
    gradientBackground: "linear-gradient(135deg, #e0f2fe 0%, #bae6fd 100%)",
    navbarColor: "#bae6fd",
    sidebarColor: "#e0f2fe",
    type: "light",
  },
   {
    name: "Velvet Twilight",
    fontFamily: "'Playfair Display', serif",
    fontColor: "#ffffff",
    backgroundColor: "#2e1065",
    slideBackgroundColor: "#4c1d95",
    accentColor: "#a855f7",
    gradientBackground: "linear-gradient(135deg, #2e1065 0%, #4c1d95 100%)",
    navbarColor: "#4c1d95",
    sidebarColor: "#2e1065",
    type: "dark",
  },
  {
    name: "Sunrise Coral",
    fontFamily: "'Poppins', sans-serif",
    fontColor: "#432818",
    backgroundColor: "#ffd7ba",
    slideBackgroundColor: "#fff3e4",
    accentColor: "#ff7d00",
    gradientBackground: "linear-gradient(135deg, #ffd7ba 0%, #ffb997 100%)",
    navbarColor: "#fff3e4",
    sidebarColor: "#ffd7ba",
    type: "light",
  },
  {
    name: "Minty Fresh",
    fontFamily: "'Quicksand', sans-serif",
    fontColor: "#1c4532",
    backgroundColor: "#d1fae5",
    slideBackgroundColor: "#ffffff",
    accentColor: "#10b981",
    gradientBackground: "linear-gradient(135deg, #d1fae5 0%, #a7f3d0 100%)",
    navbarColor: "#a7f3d0",
    sidebarColor: "#d1fae5",
    type: "light",
  },
  {
    name: "Royal Galaxy",
    fontFamily: "'Orbitron', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#0f172a",
    slideBackgroundColor: "#1e293b",
    accentColor: "#3b82f6",
    gradientBackground: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
    navbarColor: "#1e293b",
    sidebarColor: "#0f172a",
    type: "dark",
  },
  {
    name: "Golden Glow",
    fontFamily: "'Merriweather', serif",
    fontColor: "#4e342e",
    backgroundColor: "#fff8e1",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ffca28",
    gradientBackground: "linear-gradient(135deg, #fff8e1 0%, #ffe082 100%)",
    navbarColor: "#ffe082",
    sidebarColor: "#fff8e1",
    type: "light",
  },
  {
    name: "Blush Harmony",
    fontFamily: "'Lato', sans-serif",
    fontColor: "#6d4c41",
    backgroundColor: "#fce4ec",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ec407a",
    gradientBackground: "linear-gradient(135deg, #fce4ec 0%, #f8bbd0 100%)",
    navbarColor: "#f8bbd0",
    sidebarColor: "#fce4ec",
    type: "light",
  },
  {
    name: "Aqua Pulse",
    fontFamily: "'Open Sans', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#004d40",
    slideBackgroundColor: "#00695c",
    accentColor: "#00e5ff",
    gradientBackground: "linear-gradient(135deg, #004d40 0%, #00695c 100%)",
    navbarColor: "#00695c",
    sidebarColor: "#004d40",
    type: "dark",
  },
  {
    name: "Lavender Calm",
    fontFamily: "'Nunito', sans-serif",
    fontColor: "#4a148c",
    backgroundColor: "#f3e5f5",
    slideBackgroundColor: "#ffffff",
    accentColor: "#ab47bc",
    gradientBackground: "linear-gradient(135deg, #f3e5f5 0%, #e1bee7 100%)",
    navbarColor: "#e1bee7",
    sidebarColor: "#f3e5f5",
    type: "light",
  },
  {
    name: "Electric Night",
    fontFamily: "'Space Grotesk', sans-serif",
    fontColor: "#ffffff",
    backgroundColor: "#1a1a40",
    slideBackgroundColor: "#212143",
    accentColor: "#ff4081",
    gradientBackground: "linear-gradient(135deg, #1a1a40 0%, #3f3f7d 100%)",
    navbarColor: "#212143",
    sidebarColor: "#1a1a40",
    type: "dark",
  },
    {
        name: "Dark Elegance",
        fontFamily: "'Playfair Display', serif",
        fontColor: "#ffffff",
        backgroundColor: "#1a1a1a",
        slideBackgroundColor: "#2c2c2c",
        accentColor: "#ffd700",
        gradientBackground: "linear-gradient(135deg, #2c2c2c 0%, #1a1a1a 100%)",
        navbarColor: "#2c2c2c",
        sidebarColor: "#1a1a1a",
        type: "dark",
    },
    {
        name: "Nature Fresh",
        fontFamily: "'Montserrat', sans-serif",
        fontColor: "#1b4332",
        backgroundColor: "#e8f5e9",
        slideBackgroundColor: "#ffffff",
        accentColor: "#4caf50",
        gradientBackground: "linear-gradient(135deg, #e8f5e9 0%, #c8e6c9 100%)",
        navbarColor: "#c8e6c9",
        sidebarColor: "#e8f5e9",
        type: "light",
    },
    {
        name: "Tech Vibrant",
        fontFamily: "'Roboto', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#2c3e50",
        slideBackgroundColor: "#34495e",
        accentColor: "#e74c3c",
        gradientBackground: "linear-gradient(135deg, #3498db 0%, #2c3e50 100%)",
        navbarColor: "#34495e",
        sidebarColor: "#2c3e50",
        type: "dark",
    },
    {
        name: "Pastel Dream",
        fontFamily: "'Lato', sans-serif",
        fontColor: "#4a4e69",
        backgroundColor: "#f7e8e8",
        slideBackgroundColor: "#ffffff",
        accentColor: "#b5838d",
        gradientBackground: "linear-gradient(135deg, #f7e8e8 0%, #e5cece 100%)",
        navbarColor: "#e5cece",
        sidebarColor: "#f7e8e8",
        type: "light",
    },
    {
        name: "Ocean Breeze",
        fontFamily: "'Open Sans', sans-serif",
        fontColor: "#f0f8ff",
        backgroundColor: "#0077be",
        slideBackgroundColor: "#ffffff",
        accentColor: "#00a86b",
        gradientBackground: "linear-gradient(135deg, #0077be 0%, #00a86b 100%)",
        navbarColor: "#0077be",
        sidebarColor: "#005c8f",
        type: "dark",
    },
    {
        name: "Sunset Glow",
        fontFamily: "'Merriweather', serif",
        fontColor: "#3d3d3d",
        backgroundColor: "#ffd700",
        slideBackgroundColor: "#ffffff",
        accentColor: "#ff6b6b",
        gradientBackground: "linear-gradient(135deg, #ffd700 0%, #ff6b6b 100%)",
        navbarColor: "#ff6b6b",
        sidebarColor: "#ffd700",
        type: "light",
    },
    {
  name: "Minimalist Mono Dark",
  fontFamily: "'IBM Plex Mono', monospace",
  fontColor: "#f5f5f5", // Light font color for visibility on dark background
  backgroundColor: "#000000",
  slideBackgroundColor: "#1a1a1a",
  accentColor: "#ffffff",
  navbarColor: "#1a1a1a",
  sidebarColor: "#000000",
  type: "dark",
},
    {
        name: "Neon Nights",
        fontFamily: "'Orbitron', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#000000",
        slideBackgroundColor: "#1a1a1a",
        accentColor: "#00ff00",
        gradientBackground: "linear-gradient(135deg, #000000 0%, #1a1a1a 100%)",
        navbarColor: "#1a1a1a",
        sidebarColor: "#000000",
        type: "dark",
    },
    {
        name: "Earthy Tones",
        fontFamily: "'Nunito', sans-serif",
        fontColor: "#3d3d3d",
        backgroundColor: "#d7ccc8",
        slideBackgroundColor: "#f5f5f5",
        accentColor: "#795548",
        gradientBackground: "linear-gradient(135deg, #d7ccc8 0%, #a1887f 100%)",
        navbarColor: "#a1887f",
        sidebarColor: "#d7ccc8",
        type: "light",
    },
    {
        name: "Retro Pop",
        fontFamily: "'Pacifico', cursive",
        fontColor: "#1a1a1a",
        backgroundColor: "#ff4081",
        slideBackgroundColor: "#ffffff",
        accentColor: "#ffeb3b",
        gradientBackground: "linear-gradient(135deg, #ff4081 0%, #ffeb3b 100%)",
        navbarColor: "#ff4081",
        sidebarColor: "#c60055",
        type: "dark",
    },
    {
        name: "Zen Garden",
        fontFamily: "'Noto Serif JP', serif",
        fontColor: "#2f3e46",
        backgroundColor: "#f1f8e9",
        slideBackgroundColor: "#ffffff",
        accentColor: "#558b2f",
        gradientBackground: "linear-gradient(135deg, #f1f8e9 0%, #dcedc8 100%)",
        navbarColor: "#dcedc8",
        sidebarColor: "#f1f8e9",
        type: "light",
    },
    {
        name: "Arctic Frost",
        fontFamily: "'Quicksand', sans-serif",
        fontColor: "#2c3e50",
        backgroundColor: "#e0f7fa",
        slideBackgroundColor: "#ffffff",
        accentColor: "#00bcd4",
        gradientBackground: "linear-gradient(135deg, #e0f7fa 0%, #b2ebf2 100%)",
        navbarColor: "#b2ebf2",
        sidebarColor: "#e0f7fa",
        type: "light",
    },
    {
        name: "Vintage Warmth",
        fontFamily: "'Libre Baskerville', serif",
        fontColor: "#4a4a4a",
        backgroundColor: "#ffecb3",
        slideBackgroundColor: "#ffffff",
        accentColor: "#ff6f00",
        gradientBackground: "linear-gradient(135deg, #ffecb3 0%, #ffe082 100%)",
        navbarColor: "#ffe082",
        sidebarColor: "#ffecb3",
        type: "light",
    },
    {
        name: "Cosmic Delight",
        fontFamily: "'Space Grotesk', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#311b92",
        slideBackgroundColor: "#4527a0",
        accentColor: "#7c4dff",
        gradientBackground: "linear-gradient(135deg, #311b92 0%, #4527a0 100%)",
        navbarColor: "#4527a0",
        sidebarColor: "#311b92",
        type: "dark",
    },
    {
        name: "Midnight Bloom",
        fontFamily: "'Poppins', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#1a1b41",
        slideBackgroundColor: "#292a5d",
        accentColor: "#f72585",
        gradientBackground: "linear-gradient(135deg, #1a1b41 0%, #292a5d 100%)",
        navbarColor: "#292a5d",
        sidebarColor: "#1a1b41",
        type: "dark",
    },
    {
        name: "Coral Sunset",
        fontFamily: "'Raleway', sans-serif",
        fontColor: "#33272a",
        backgroundColor: "#feeafa",
        slideBackgroundColor: "#ffffff",
        accentColor: "#ff9a8b",
        gradientBackground: "linear-gradient(135deg, #feeafa 0%, #ff9a8b 100%)",
        navbarColor: "#feeafa",
        sidebarColor: "#fff0f5",
        type: "light",
    },
    {
        name: "Emerald City",
        fontFamily: "'Montserrat', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#064e3b",
        slideBackgroundColor: "#065f46",
        accentColor: "#34d399",
        gradientBackground: "linear-gradient(135deg, #064e3b 0%, #065f46 100%)",
        navbarColor: "#065f46",
        sidebarColor: "#064e3b",
        type: "dark",
    },
    {
        name: "Lavender Mist",
        fontFamily: "'Nunito', sans-serif",
        fontColor: "#4a4e69",
        backgroundColor: "#f3e8ff",
        slideBackgroundColor: "#ffffff",
        accentColor: "#9f7aea",
        gradientBackground: "linear-gradient(135deg, #f3e8ff 0%, #e9d5ff 100%)",
        navbarColor: "#e9d5ff",
        sidebarColor: "#f3e8ff",
        type: "light",
    },
    {
        name: "Golden Hour",
        fontFamily: "'Source Sans Pro', sans-serif",
        fontColor: "#3d3d3d",
        backgroundColor: "#fef3c7",
        slideBackgroundColor: "#ffffff",
        accentColor: "#f59e0b",
        gradientBackground: "linear-gradient(135deg, #fef3c7 0%, #fde68a 100%)",
        navbarColor: "#fde68a",
        sidebarColor: "#fef3c7",
        type: "light",
    },
    {
        name: "Arctic Aurora",
        fontFamily: "'Roboto', sans-serif",
        fontColor: "#e2e8f0",
        backgroundColor: "#0f172a",
        slideBackgroundColor: "#1e293b",
        accentColor: "#38bdf8",
        gradientBackground: "linear-gradient(135deg, #0f172a 0%, #1e293b 100%)",
        navbarColor: "#1e293b",
        sidebarColor: "#0f172a",
        type: "dark",
    },
    {
        name: "Sakura Blossom",
        fontFamily: "'Noto Sans JP', sans-serif",
        fontColor: "#5d576b",
        backgroundColor: "#fff5f5",
        slideBackgroundColor: "#ffffff",
        accentColor: "#f687b3",
        gradientBackground: "linear-gradient(135deg, #fff5f5 0%, #fed7e2 100%)",
        navbarColor: "#fed7e2",
        sidebarColor: "#fff5f5",
        type: "light",
    },
    {
        name: "Urban Jungle", fontFamily: "'Karla', sans-serif",
        fontColor: "#2d3748",
        backgroundColor: "#e6fffa",
        slideBackgroundColor: "#ffffff",
        accentColor: "#2c7a7b",
        gradientBackground: "linear-gradient(135deg, #e6fffa 0%, #b2f5ea 100%)",
        navbarColor: "#b2f5ea",
        sidebarColor: "#e6fffa",
        type: "light",
    },
    {
        name: "Cosmic Latte",
        fontFamily: "'Work Sans', sans-serif",
        fontColor: "#3d3d3d",
        backgroundColor: "#fff8e1",
        slideBackgroundColor: "#ffffff",
        accentColor: "#d97706",
        gradientBackground: "linear-gradient(135deg, #fff8e1 0%, #fef3c7 100%)",
        navbarColor: "#fef3c7",
        sidebarColor: "#fff8e1",
        type: "light",
    },
    {
        name: "Neon Cyberpunk",
        fontFamily: "'Rajdhani', sans-serif",
        fontColor: "#ffffff",
        backgroundColor: "#09090b",
        slideBackgroundColor: "#18181b",
        accentColor: "#22d3ee",
        gradientBackground: "linear-gradient(135deg, #09090b 0%, #18181b 100%)",
        navbarColor: "#18181b",
        sidebarColor: "#09090b",
        type: "dark",
    },
];





export const layouts: LayoutGroup[] = [
  {
    name: "Basic",
    layouts: [
      {
        name: "Blank card",
        icon: BlankCardIcon,
        type: "layout",
        layoutType: "blank-card",
        component: BlankCard,
      },
      {
        name: "Image and text",
        icon: ImageAndTextIcon,
        type: "layout",
        layoutType: "imageAndText",
        component: ImageAndText,
      },
      {
        name: "Text and image",
        icon: TextAndImageIcon,
        type: "layout",
        layoutType: "textAndImage",
        component: TextAndImage,
      },
      {
        name: "Two Columns",
        icon: TwoColumnsIcon,
        type: "layout",
        layoutType: "twoColumns",
        component: TwoColumns,
      },
      {
        name: "Two Columns with headings",
        icon: TwoColumnsWithHeadingsIcon,
        type: "layout",
        layoutType: "twoColumnsWithHeadings",
        component: TwoColumnsWithHeadings,
      },
      {
        name: "Three Columns",
        icon: ThreeColumnsIcon,
        type: "layout",
        layoutType: "threeColumns",
        component: ThreeColumns,
      },
      {
        name: "Three Columns with headings",
        icon: ThreeColumnsWithHeadingsIcon,
        type: "layout",
        layoutType: "threeColumnsWithHeadings",
        component: ThreeColumnsWithHeadings,
      },

      {
        name: "Four Columns",
        icon: FourColumnsIcon,
        type: "layout",
        layoutType: "fourColumns",
        component: FourColumns,
      },
    ],
  },

  {
    name: "Card layouts",
    layouts: [
      {
        name: "Accent left",
        icon: ImageAndTextIcon,
        type: "layout",
        layoutType: "accentLeft",
        component: AccentLeft,
      },
      {
        name: "Accent right",
        icon: TextAndImageIcon,
        type: "layout",
        layoutType: "accentRight",
        component: AccentRight,
      },
    ],
  },

  {
    name: "Images",
    layouts: [
      {
        name: "2 images columns",
        icon: TwoImageColumnsIcon,
        type: "layout",
        layoutType: "twoImageColumns",
        component: TwoImageColumns,
      },
      {
        name: "3 images columns",
        icon: ThreeImageColumnsIcon,
        type: "layout",
        layoutType: "threeImageColumns",
        component: ThreeImageColumns,
      },
      {
        name: "4 images columns",
        icon: FourImageColumnsIcon,
        type: "layout",
        layoutType: "fourImageColumns",
        component: FourImageColumns,
      },
    ],
  },
];

export const CreatePageCard = [
    {
        title: 'Use a',
        highlightedText: 'Template',
        description: 'Write a prompt and leave everything else for us to handle',
        type: 'template',
    },
    {
        title: 'Generate with',
        highlightedText: 'Creative AI',
        description: 'Write a prompt and leave everything else for us to handle',
        type: 'creative-ai', 
        highlight:true
    },

  { title: 'Create from',
    highlightedText: 'Scratch',
    description: 'Write a prompt and leave everything else for us to handle',
    type: 'create-scratch',
}
]

export const createSlideFromLayout = (layoutType: string): LayoutSlides => {
  switch (layoutType) {
    case "blank-card":
      return BlankCard;
    case "accentLeft":
      return AccentLeft;
    case "accentRight":
      return AccentRight;
    case "imageAndText":
      return ImageAndText;
    case "textAndImage":
      return TextAndImage;
    default:
      return BlankCard;
  }
};

export const component: ComponentGroup[] = [
  {
    name: "Text",
    components: [
      {
        name: "Title",
        icon: "T",
        type: "component",
        component: Title,
        componentType: "title",
      },
      {
        componentType: "heading1",
        name: "Heading 1",
        type: "component",
        component: Heading1,
        icon: "H1",
      },
      {
        componentType: "heading2",
        name: "Heading 2",
        type: "component",
        component: Heading2,
        icon: "H2",
      },
      {
        componentType: "heading3",
        name: "Heading 3",
        type: "component",
        component: Heading3,
        icon: "H3",
      },
      {
        componentType: "heading4",
        name: "Heading 4",
        type: "component",
        component: Heading4,
        icon: "H4",
      },

      {
        componentType: "paragraph",
        name: "Paragraph",
        type: "component",
        component: Paragraph,
        icon: "Paragraph",
      },
    ],
  },

  {
    name: "Tables",
    components: [
      {
        componentType: "table2x2",
        name: "2×2 table",
        type: "component",
        component: { ...Table, initialColumns: 2, initialRows: 2 },
        icon: "⊞",
      },
      {
        componentType: "table3x3",
        name: "3×3 table",
        type: "component",
        component: { ...Table, initialColumns: 3, initialRows: 3 },
        icon: "⊞",
      },
      {
        componentType: "table4x4",
        name: "4×4 table",
        type: "component",
        component: { ...Table, initialColumns: 4, initialRows: 4 },
        icon: "⊞",
      },
    ],
  },

  {
    name: "Lists",
    components: [
      {
        componentType: "bulletList",
        name: "Bulleted list",
        type: "component",
        component: BulletListComponent,
        icon: "•",
      },
      {
        componentType: "numberedList",
        name: "Numbered list",
        type: "component",
        component: NumberedListComponent,
        icon: "1.",
      },
      {
        componentType: "todoList",
        name: "Todo list",
        type: "component",
        component: TodoListComponent,
        icon: "☐",
      },
    ],
  },
  {
    name: "Callouts",
    components: [
      {
        componentType: "note",
        name: "Note box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "info" },
        icon: "📝",
      },
      {
        componentType: "info",
        name: "Info box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "info" },
        icon: "ℹ",
      },
      {
        componentType: "warning",
        name: "Warning box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "warning" },
        icon: "⚠",
      },
      {
        componentType: "caution",
        name: "Caution box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "caution" },
        icon: "⚠",
      },
      {
        componentType: "success",
        name: "Success box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "success" },
        icon: "✓",
      },
      {
        componentType: "question",
        name: "Question box",
        type: "component",
        component: { ...CalloutBoxComponent, callOutType: "question" },
        icon: "?",
      },
    ],
  },

  {
    name: "Columns",
    components: [
      {
        componentType: "resizableColumns",
        name: "2x2 Column",
        type: "component",
        component: ResizableColumn,
        icon: "⊞",
      },
    ],
  },
];