// 'use client'

// import StrokeEarth from '@/icons/StrokeEarth'
// import React from 'react'

// export default function NotFound() {
//   return (
//     <div
//       style={{
//         position: 'fixed',
//         top: '60%',
//         left: '50%',
//         transform: 'translate(-50%, -50%)',
//         width: '90vw',
//         maxWidth: 480,
//       }}
//       className="bg-transparent p-6 flex flex-col items-center"
//     >
      
//       <p className="text-3xl font-semibold text-primary mt-6 text-center">
//         Nothing to see here
//       </p>
//       <div className="mt-2 text-center text-xl font-normal" style={{ color: '#aaa' }}>
//         <p>So here is a random image generated by</p>
//         <p className="text-vivid font-semibold mt-1">Creative AI</p>
//       </div>
//     </div>
//   )
// }


export default function NotFound() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen text-center">
      <p className="text-2xl md:text-3xl font-semibold text-primary">
        Nothing to see here
      </p>
      <div className="mt-2 text-lg md:text-xl text-gray-400">
        <p>So here is a random image generated by</p>
        <p className="text-vivid font-semibold mt-1">Creative AI</p>
      </div>
    </div>
  );
}
